namespace MediatR.Endpoints;

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
public class EndpointAttribute : Attribute, IEndpointDefinition
{ 
    /// <summary>
    /// Register an endpoint
    /// </summary>
    /// <param name="httpMethod">The HTTP Method</param>
    /// <param name="route">The route pattern. If omitted, route is generated by <see cref="MediatREndpointsConfiguration.DefaultRouteFormatter"/></param>
    public EndpointAttribute(Method httpMethod, string route = null)
    {
        HttpMethod = httpMethod;
        Route = route;        
    }     
    public Method HttpMethod { get; set; }
    public string Route { get; set; }
    public string Group { get; set; } = "";  
}


